[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[package]
disabled = true

[nodejs]
format = "[⬢ $version](bold) "

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
